### ISSUE TITLE
broken link, redundant code [?]. terminology error

### ISSUE THREAD

**Issue by asl97** [fagga/transmission-remote-cli#149]
i am making this issue mainly because of the broken links, but since i am making it, i thought maybe i should point out the other stuff.

- [x] dead links in readme, the fedora and COPYING link
- [ ] cli stand for Command Line Interface
- [x] [line 1030](https://github.com/fagga/transmission-remote-cli/blob/master/transmission-remote-cli#L1030) in transmission-remote-cli [?]

**Comment by fagga** [comment]
> - [ ] dead link in readme, the fedora and COPYING link

Thanks, fixed.

> - [ ] cli stand for Command Line Interface

This is a known bug and has been pointed out several times, but I don't think
this is serious enough to go through the name-changing process.

> - [ ] [line 1030](https://github.com/fagga/transmission-remote-cli/blob/master/transmission-remote-cli#L1030) in transmission-remote-cli [?]

This seems to be a workaround for a bug.

**Comment by asl97** [comment]
@fagga i am talking about the duplicate code for the line 1030 and 1037

i don't think it was suggested to repeat the code twice and i wouldn't be surprise if the second `try except` doesn't do anything except raise an `KeyError` in it.

**Comment by fagga** [comment]
All I can remember is that the code was provided as it is now (including the
duplication) as a bugfix by someone else. I have no idea how to find that
commit.

I agree that it looks completely redundant, but it also doesn't do much harm
besides adding a few microseconds (if that) to the startup time. I'd rather
not touch it to avoid a regression.

**Comment by asl97** [comment]
you can just use git blame, the paste/diff the bugfix someone gave only has one copy, https://github.com/fagga/transmission-remote-cli/issues/37#issuecomment-3712959  

the reason why there are two copy of the code is because instead of merging the branch with the fi, you manually commit it in `master` and when you merge the other branch into `master`, there become two copy of it,  here is the commit that added it https://github.com/fagga/transmission-remote-cli/commit/355a270ddb5c69524c2cdd4d8b3869f8721d4175#diff-bf4cba222f9ab6f11e9cb817901a4761R839

**Comment by fagga** [comment]
You are a wizzard! Thanks for the lesson.

I removed the duplicate.
