### ISSUE TITLE
Graphic broken given 'TERM=xterm-256color' under tmux

### ISSUE THREAD

**Issue by quillkiragimmy** [fagga/transmission-remote-cli#152]
## In brief: ##
* Partially screen update when scrolling if TERM='xterm-256color' & run in tmux.
* Tested under several machines & term-emulators, versions, but not older ncurses.

## In detail: ##
I started using vim-powerline setting yesterday ( which needs the $TERM to be set to 'xterm-256color' ) and found the window contents in transmission-remote-cli only updated by six lines in scrolled direction ( that is: last six lines if I scroll down ) when scrolling if launched in tmux.

The older versions also have the same problem no matter it's run under tty or term-emulator. The term-emulators I've tried on are Gnome-term & xfce4-term & xterm.

Other ncurses programs work fine with tmux ( mc, ncmpcpp, ncdu... ), and the wonky behaviour still exist even when using default tmux settings. Due to forementioned reasons I think this could be a suspicious bug of transmission-remote-cli.

I recently have my package cache purged, so I can't test on older ncurses lib. Currently using a workaround to switch $TERM between 'screen' and 'xterm-256colour' when launching transmission-remote-cli.

**Comment by quillkiragimmy** [comment]
Well, this issue just magically disappeared after using 'screen-256color' instead of 'xterm-256color'. Yes, I know this kind of solution sucks on many level, but finding what's going wrong can be a hair pulling chore.

Maybe someone with enough virtue and valor will sort this out eventually.

**Comment by fagga** [comment]
Why does this solution suck? There are different '*-256color' modes for
different terminal emulators (I'm using rxvt-unicode-256color). It makes sense
to me that abstraction layers like screen and tmux may need some adjustments.

With that said, it's probably a bug in trcli. It was a bad idea from the very
beginning to use bare curses.

**Comment by quillkiragimmy** [comment]
You're right. Maybe I'm a little too obstinate to this.
It makes me feel like using a magic number in the code when I need to avoid an ubiquitous setting to fix something. I need to write a comment in my bashrc like: '  Don't touch! Magic.' to prevent myself from accidentally changing it back.
( AFAIK only 'screen-256color' works for 256 colours and scrolling, that's kind of hilarious. )

I thought trcli is using ncurses ( which apparently not ) when I fired that issue, and other programs working fine is using ncurses. So this might be a bug between tmux and curses lib.

Is there any plan of moving to ncurses?

**Comment by fagga** [comment]
If you're using a terminal multiplexer, why would you change your $TERM to
xterm-256color in the first place? It's made for xterms, not for screen or
tmux. Maybe I'm just a little dense here. My knowledge about terminals is
pretty limited.

But I'm fairly sure that ncurses is just an implementation of curses, and that
Python wraps ncurses with their curses module.

**Comment by quillkiragimmy** [comment]
I set it to xterm-256color just because of my ignorance about tmux... Actually tmux uses 'screen' as default. I'll add a '256color' entry to my tmux.conf, which should fix this problem flawlessly.

Thank you for your replies. I'm a noob to curses lib. I'll close this issue if thing goes smoothly. :)
